### ISSUE TITLE
i'm have error

### ISSUE THREAD

**Issue by idkplayer** [ijre/Osiris#3]
#include "stdafx.h"

**Comment by ijre** [comment]
Do you have "stdafx.h" located at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\atlmfc\src\atl\atls ?

**Comment by idkplayer** [comment]
I do not own it, I have to download it?

**Comment by ijre** [comment]
Yeah, it comes with visual studio; you might be able to find a standalone version but I'm not sure
Visual Studio is free though, so if you can't find it solo don't worry and just download visual studio

**Comment by idkplayer** [comment]
Sorry i have "stdafx.h"

**Comment by ijre** [comment]
Where at? And also I forgot to ask, what file(s) is/are giving you the error?

**Comment by idkplayer** [comment]
in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\atlmfc\src\atl\atls, everywhere this error.

**Comment by ijre** [comment]
Alright, are you using Visual Studio to compile?

**Comment by idkplayer** [comment]
Yes

**Comment by idkplayer** [comment]
e.g error C1010:  unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?

**Comment by ijre** [comment]
In the project settings, in the option i think called "VC directories", what does it say for your include directories setting

**Comment by ijre** [comment]
Okay, so this same error just happened to me too randomly, and I have two solutions, one that worked for me, and one that is easier but only came to me later so it might not work

The second solution is:
Go into the project settings, go to C/C++, then go into precompiled headers
Set "precompiled header" to "dont use precompiled headers"
Then just compile

If this doesn't work:
If Osiris is open, close the solution at the top left with the option named file
Delete every file named Osiris in the root folder **_EXCEPT_** for Osiris.cpp and Osiris.h
Then, go back to file at the top left, go to new, then "project using existing code" and follow the instructions
You don't need to do anything special EXCEPT make sure that where it says "project type" you set it to "DLL project (Dynamically Linked Library)"

**Comment by ijre** [comment]
As you haven't responded if this worked or not, I'll close this for now so it's out of the way; feel free to reopen it if my solution didn't help though. (if you can, im not actually sure if you can reopen issues which the repo owner closes)
